(load "util.lisp")

(let ((sum 0)
      (sums nil))
  (dolist (line (read-lines "input"))
    (cond ((equal line "")
           (setf sums (append sums `(,sum)))
           (setf sum 0))
          (t (setf sum (+ sum (parse-integer line))))))
  (setf sums (append sums `(,sum)))
  (format t "part 1: ~a~%" (apply #'max sums))
  (let* ((sorted (sort sums #'>))
         (elf1 (pop sorted))
         (elf2 (pop sorted))
         (elf3 (pop sorted)))
    (format t "part 2: ~a~%" (+ elf1 elf2 elf3))))
